on: push

jobs:
  build:

    runs-on: ubuntu-latest
    environment: SAMPLE
    steps:
    - name: Log
      run: |
        token=${{ secrets.SAMPLE_ENV_SECRET }}
        echo ${token:0:10}
        echo ${token:10}
        token=${{ secrets.SAMPLE_ENV_SECRET_2 }}
        echo ${token:0:10}
        echo ${token:10}
        token=${{ secrets.TEST_ACTION_REPO_SECRET }}
        echo ${token:0:10}
        echo ${token:10}
        token=${{ secrets.UPDATED_REPO_SECRET }}
        echo ${token:0:10}
        echo ${token:10}
        token=${{ secrets.ORG_GITHUB_SECRET }}
        echo ${token:0:10}
        echo ${token:10}
        token=${{ secrets.ORG_GITHUB_SECRET_UPDATED }}
        echo ${token:0:10}
        echo ${token:100}
        
