name: test-vars

on: pull_request

jobs:
  display-variables:
    environment: SAMPLE
    runs-on: ubuntu-latest
    steps:        
    - name: Use variables
      run: |
        echo "org variable : ${{ vars.SAMPLE_ORG_VAR_2 }}"
        echo "repo variable : ${{ vars.SAMPLE_REPO_VAR }}"
        echo "env variable : ${{ vars.SAMPLE_ENV_VAR }}"
