name: CI
on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    environment: SAMPLE
    steps:
    - uses: Sample-Ganes-Org/hello-world-action@main
      with:
        who-to-greet: "Ganesh"
      
        
